objects/Boat__c.object
<CustomObject>
    <fields>
        <fullName>BoatType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Boat Type</label>
        <referenceTo>BoatType__c</referenceTo>
        <relationshipLabel>Boats</relationshipLabel>
        <relationshipName>Boats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Boats</relationshipLabel>
        <relationshipName>Boats</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <type>Url</type>
    </fields>
    <label>Boat</label>
    <nameField>
        <label>Boat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BoatType__c.object
<CustomObject>
    <label>Boat Type</label>
    <nameField>
        <label>Boat Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boat Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BoatSearchResults.cls
public with sharing class BoatSearchResults {
    @AuraEnabled
    public static List<Boat__c> getBoats(String boatTypeId){ 
        List<Boat__c> boats = new List<Boat__c>();
        if(String.isEmpty(boatTypeId)){
            boats = [Select Id,Name,BoatType__c,Contact__r.Name,Picture__c,Geolocation__Latitude__s,Geolocation__Longitude__s From Boat__c];
            return boats;
        }
        else {
            Id myId = Id.valueOf(boatTypeId);
            boats = [Select Id,Name,BoatType__c,Contact__r.Name,Picture__c,Geolocation__Latitude__s,Geolocation__Longitude__s From Boat__c where BoatType__c=:myId];
            return boats;     
        }
            
    }
}