objects/Case.object
<CustomObject>
    <fields>
        <fullName>Date_Due__c</fullName>
        <label>Date Due</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Reported__c</fullName>
        <label>Date Reported</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment to be Serviced</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/MaintenanceRequestTest.cls
@istest
private class MaintenanceRequestTest {
    @istest
    public static Case createMaintenaceRequest()
    {
        Case testCase = new Case();
        Date newDate = Date.today();
        testCase.Type = 'Routine Maintenance';
        testCase.Status = 'New';
        testCase.Origin = 'Email'; 
        testCase.Date_Reported__c = Date.today();
        testCase.Subject = 'Routine Maintenance';
        testCase.Vehicle__c = 'a0Ef400000sf3BFEAY';
        testCase.Equipment__c = '01tf4000004BaxAAAS';
        testCase.Date_Due__c = newDate.addDays(90);
        insert testCase;
        return testCase;
    }
    @istest
    public static void updateMaintenanceRequest()
    {
        Case cas = createMaintenaceRequest();
        cas.Status = 'Closed';
        update cas;
    }
}