objects/Case.object
<CustomObject>
    <fields>
        <fullName>Date_Due__c</fullName>
        <label>Date Due</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Reported__c</fullName>
        <label>Date Reported</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment to be Serviced</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Maintenance_Cycle__c</fullName>
        <description>Number of days required before routine maintenance is needed</description>
        <label>Maintenance Cycle (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Work_Part__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>No spare parts meet this description or name.</errorMessage>
            <filterItems>
                <field>Product2.Replacement_Part__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Work Parts</relationshipLabel>
        <relationshipName>Work_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maintenance_Request__c</fullName>
        <label>Maintenance Request</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Work Parts</relationshipLabel>
        <relationshipName>Work_Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Work Part</label>
    <nameField>
        <displayFormat>PART-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MaintenanceRequestHelper.cls
public with sharing class MaintenanceRequestHelper {
    
    public static void updateWorkOrders(List<Case> mr) {
        List<ID> newMr = new List<ID>();
        List<Case> mrList = new List<Case>();
        for(Case c: mr)
        { 
            if(c.Type == 'Routine Maintenance' && c.status == 'Closed')
            {
               newMr.add(c.Id);
               mrList.add(c);
            }
        }
        createCase(newMr,mrList);
        
    }       
	private static void createCase(List<ID> newMr,List<Case> mrList)
    {
     List<Work_Part__c> wp = getWorkpart(newMr);
     List<Case> maintenanceRequest = new List<Case>();
         for(Case c : mrList)
         {
            Case newMaintencerequest = new Case();
            Date newDate = Date.today();
            //Decimal days = wp.Equipment__r.Maintenance_Cycle__c;
            newMaintencerequest.Type = 'Routine Maintenance';
            newMaintencerequest.Status = 'New';
            newMaintencerequest.Origin = 'Email'; 
            newMaintencerequest.Date_Reported__c = Date.today();
            newMaintencerequest.Subject = 'Routine Maintenance';
            newMaintencerequest.Vehicle__c = c.Vehicle__c;
            newMaintencerequest.Equipment__c = c.Equipment__c;
            newMaintencerequest.Date_Due__c = newDate.addDays(90);
            maintenanceRequest.add(newMaintencerequest);
         }
        insert maintenanceRequest;
        
    }
    private static List<Work_Part__c> getWorkpart(List<ID> newMr)
    {
        List<Work_Part__c> wp = [Select Id,Name,Equipment__r.Maintenance_Cycle__c From Work_Part__c Where Maintenance_Request__c IN :newMr];
        
        return wp;
    }
}