objects/LicenseApplication__c.object
<CustomObject>
    <label>LicenseApplication</label>
    <nameField>
        <label>LicenseApplication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LicenseApplications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PortalAdminRequest__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Invited</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>PortalAdminRequest</label>
    <nameField>
        <label>PortalAdminRequest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PortalAdminRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PortalAdminService.cls
public with sharing class PortalAdminService {
    
    public static void processPortalAdmin(List<LicenseApplication__c> licenseAppication)
    {
        System.debug('Future call begins');
        processPortalAdminService(licenseAppication[0].Id);
    }

    @future
    public static void processPortalAdminService(ID licenseApplicationId)
    {
        List<LicenseApplication__c> licenseApplication = [Select ID,Name from LicenseApplication__c where Id =:licenseApplicationId];

        PortalAdminRequest__c portalAdminReq = new PortalAdminRequest__c();
        portalAdminReq.Name = 'Test'; 
        portalAdminReq.status__c = 'Draft';
        insert portalAdminReq; 
  
        System.debug('License application ID ' + licenseApplicationId);
        System.debug('Portal Admin Request ' + portalAdminReq);

        for(LicenseApplication__c la: licenseApplication)
        {
            if(la.Name == 'Second Application')
            {
                portalAdminReq.status__c = 'Approved';
                update portalAdminReq;
            }
        }
        System.debug('Portal Admin Request ' + portalAdminReq);
    }
}