objects/RouteSearch__c.object
<CustomObject>
    <fields>
        <fullName>Available__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Location__c</fullName>
        <label>End Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Melbourne</fullName>
                </value>
                <value>
                    <fullName>Sydney</fullName>
                </value>
                <value>
                    <fullName>Canberra</fullName>
                </value>
                <value>
                    <fullName>Adelaide</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Location__c</fullName>
        <label>Start Location</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Melbourne</fullName>
                </value>
                <value>
                    <fullName>Sydney</fullName>
                </value>
                <value>
                    <fullName>Canberra</fullName>
                </value>
                <value>
                    <fullName>Adelaide</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>RouteSearch</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>RouteSearch Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RouteSearches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RouteSearch.cls
@RestResource(urlMapping='/routesearch/*')
global with sharing class RouteSearch {
    @HttpGet
    global static RouteSearch__c doGet() {
	   RestRequest request = RestContext.request;

	   String a = request.params.get('CityA');
	   String b = request.params.get('CityB');
	   System.debug(a);	
	   System.debug(b);
       List<RouteSearch__c> r = [SELECT Start_Location__c, Available__c, End_Location__c, Id FROM RouteSearch__c Where Start_Location__c =:a];
	   Boolean avail = r[0].Available__c;
	   System.debug(avail);	
	   return r[0];
}
}