objects/Train__c.object
<CustomObject>
    <fields>
        <fullName>Train_Name__c</fullName>
        <label>Train Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Train</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Train Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trains</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Train_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Train__c</fullName>
        <label>Train</label>
        <referenceTo>Train__c</referenceTo>
        <relationshipLabel>Train Schedules</relationshipLabel>
        <relationshipName>Train_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Train Schedule</label>
    <nameField>
        <label>Train Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Train Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CheckTrainschedule.cls
public class CheckTrainschedule {

public static void addTrain()
{
List <Train__c> Tra = new List<Train__c>();
List <Train_Schedule__c> tras = new List<Train_Schedule__c>();

	for (Integer i = 0; i < 50 ; i++)
	{
	   tra.add(new Train__C(Train_name__C = 'Train'+ i));
	}
	Insert Tra;

	for (Integer i = 0; i < 50 ; i++)
	{
	   tras.add(new Train_Schedule__c(Name = 'Train Schedule'+ i,Train__c = tra[i].Id));
	}
	Insert tras;
}

}