objects/Train__c.object
<CustomObject>
    <fields>
        <fullName>Train_Name__c</fullName>
        <label>Train Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Train</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Train Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trains</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/CheckTrainschedule_Test.cls
@isTest
private class CheckTrainschedule_Test{
  @testSetup
  static void setupTestData(){
    test.startTest();
    Train__c train_Obj = new Train__c(Train_Name__c = 'Train658');
    Insert train_Obj; 
    test.stopTest();
  }
  static testMethod void test_addTrain_UseCase1(){
    List<Train__c> train_Obj  =  [SELECT Name,Train_Name__c from Train__c];
    System.assertEquals(true,train_Obj.size()>0);
    CheckTrainschedule obj01 = new CheckTrainschedule();
    CheckTrainschedule.addTrain();
  }
}